# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tts_interface_pb2 as tts__interface__pb2


class cloneStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inference = channel.unary_stream(
                '/ttsserver.clone/Inference',
                request_serializer=tts__interface__pb2.TtsServiceRequest.SerializeToString,
                response_deserializer=tts__interface__pb2.Response.FromString,
                )
        self.StreamInference = channel.stream_stream(
                '/ttsserver.clone/StreamInference',
                request_serializer=tts__interface__pb2.TtsServiceRequest.SerializeToString,
                response_deserializer=tts__interface__pb2.Response.FromString,
                )
        self.RegisterSpk = channel.unary_unary(
                '/ttsserver.clone/RegisterSpk',
                request_serializer=tts__interface__pb2.RegisterSpeakerRequest.SerializeToString,
                response_deserializer=tts__interface__pb2.Response.FromString,
                )


class cloneServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Inference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInference(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterSpk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_cloneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inference': grpc.unary_stream_rpc_method_handler(
                    servicer.Inference,
                    request_deserializer=tts__interface__pb2.TtsServiceRequest.FromString,
                    response_serializer=tts__interface__pb2.Response.SerializeToString,
            ),
            'StreamInference': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamInference,
                    request_deserializer=tts__interface__pb2.TtsServiceRequest.FromString,
                    response_serializer=tts__interface__pb2.Response.SerializeToString,
            ),
            'RegisterSpk': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSpk,
                    request_deserializer=tts__interface__pb2.RegisterSpeakerRequest.FromString,
                    response_serializer=tts__interface__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ttsserver.clone', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class clone(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Inference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ttsserver.clone/Inference',
            tts__interface__pb2.TtsServiceRequest.SerializeToString,
            tts__interface__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamInference(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ttsserver.clone/StreamInference',
            tts__interface__pb2.TtsServiceRequest.SerializeToString,
            tts__interface__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterSpk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ttsserver.clone/RegisterSpk',
            tts__interface__pb2.RegisterSpeakerRequest.SerializeToString,
            tts__interface__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
