# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tts_interface.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13tts_interface.proto\x12\tttsserver\"\x95\x01\n\x16RegisterSpeakerRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nspeaker_id\x18\x03 \x01(\t\x12\x1a\n\x12upload_prompt_text\x18\x04 \x01(\t\x12\x12\n\nprompt_wav\x18\x05 \x01(\x0c\x12\x12\n\nprompt_num\x18\x06 \x01(\x05\"\xd4\x01\n\x11TtsServiceRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\n \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nspeaker_id\x18\x03 \x01(\t\x12\x0e\n\x06if_ver\x18\x04 \x01(\r\x12\x13\n\x0bspeed_ratio\x18\x05 \x01(\x02\x12\x14\n\x0cvolume_ratio\x18\x06 \x01(\x02\x12\x13\n\x0bsample_rate\x18\x07 \x01(\r\x12\x16\n\x0estreaming_mode\x18\x08 \x01(\x08\x12\x10\n\x08\x65ncoding\x18\t \x01(\t\"\x88\x01\n\x08Response\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x65ncoding\x18\x02 \x01(\t\x12\x14\n\x0cResultStatus\x18\x03 \x01(\r\x12\x0b\n\x03Msg\x18\x04 \x01(\t\x12\x13\n\x0bsample_rate\x18\x05 \x01(\r\x12\x10\n\x08sequence\x18\x06 \x01(\x05\x12\x0c\n\x04\x41IGC\x18\x07 \x01(\t2\xe0\x01\n\x05\x63lone\x12\x42\n\tInference\x12\x1c.ttsserver.TtsServiceRequest\x1a\x13.ttsserver.Response\"\x00\x30\x01\x12J\n\x0fStreamInference\x12\x1c.ttsserver.TtsServiceRequest\x1a\x13.ttsserver.Response\"\x00(\x01\x30\x01\x12G\n\x0bRegisterSpk\x12!.ttsserver.RegisterSpeakerRequest\x1a\x13.ttsserver.Response\"\x00\x42\tZ\x07protos/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_interface_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007protos/'
  _globals['_REGISTERSPEAKERREQUEST']._serialized_start=35
  _globals['_REGISTERSPEAKERREQUEST']._serialized_end=184
  _globals['_TTSSERVICEREQUEST']._serialized_start=187
  _globals['_TTSSERVICEREQUEST']._serialized_end=399
  _globals['_RESPONSE']._serialized_start=402
  _globals['_RESPONSE']._serialized_end=538
  _globals['_CLONE']._serialized_start=541
  _globals['_CLONE']._serialized_end=765
# @@protoc_insertion_point(module_scope)
